import Head from 'next/head';
import CarouselBanner from '../components/CarouselBanner';
import Header from '../components/Header';
import ProductFeed from '../components/ProductFeed';
import { getSession } from 'next-auth/client';

export default function Home({ products }) {
    return (
        <div className="bg-gray-100">
            <Head>
                <title>Amazon Clone | Nextjs, Tailwind CSS</title>
                <meta name="Amazon clone" content="Generated by create Next.js and Tailwind CSS" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="max-w-screen-2xl mx-auto">
                {/* carousel banner */}
                <CarouselBanner />

                {/* product feed */}
                <ProductFeed products={products} />
            </main>
        </div>
    );
}

export async function getServerSideProps(context) {
    const session = await getSession(context);
    const products = await fetch('https://fakestoreapi.com/products').then((res) => res.json());

    return {
        props: {
            products,
            session,
        },
    };
}
